# This is a basic workflow that is manually triggered

name: Make PR for Mobile

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
